keys:
  - &vanilla age1qcw4ynnhxcy8rfvx7rcfelg44esxsq20ke649x0anmw03zts0vpqd2wuwj
  - &nixos-rot age1wsm66wfr48tchca8g8q39002x2v3yc76t8zqvekh3h2h86fdfyyq05uy5t
creation_rules:
  - path_regex: secrets/[^/]+\.yaml$
    key_groups:
      - age:
          - *vanilla
          - *nixos-rot
