keys:
  - &vanilla 2649 340C C909 F821 D251  6714 3750 028E D04F A42E
  - &nixos-rot e3520a257213e7f48a3f5459c7108941f87e771f

creation_rules:
  - path_regex: secrets/[^/]+\.yaml$

    key_groups:
      - pgp:
          - *vanilla
          - *nixos-rot
