[oh-my-posh]
src.github = "JanDeDobbeleer/oh-my-posh"
fetch.github = "JanDeDobbeleer/oh-my-posh"

[rose-pine]
src.git = "https://github.com/rose-pine/alacritty"
fetch.git = "https://github.com/rose-pine/alacritty"

[hwatch]
# the given path has multiple possibilities
src.git = "https://github.com/blacknon/hwatch"
fetch.git = "https://github.com/blacknon/hwatch"
