[rose-pine]
src.git = "https://github.com/rose-pine/alacritty"
fetch.git = "https://github.com/rose-pine/alacritty"

[plugin-kubectl]
src.git = "https://github.com/blackjid/plugin-kubectl"
fetch.git = "https://github.com/blackjid/plugin-kubectl"

# [Boxfish]
# src.git = "https://github.com/MidAutumnMoon/Boxfish"
# fetch.git = "https://github.com/MidAutumnMoon/Boxfish"

# https://github.com/brunonova/nautilus-admin

[nautilus-admin]
src.github_tag = "brunonova/nautilus-admin"
fetch.github = "brunonova/nautilus-admin"

# https://github.com/madmurphy/nautilus-bluetooth

[nautilus-bluetooth]
src.github_tag = "madmurphy/nautilus-bluetooth"
fetch.github = "madmurphy/nautilus-bluetooth"

# https://github.com/flozz/nautilus-terminal

[nautilus-terminal]
src.github_tag = "flozz/nautilus-terminal"
fetch.github = "flozz/nautilus-terminal"

# https://github.com/bilelmoussaoui/nautilus-git/pull/45

[nautilus-git]
src.git = "https://github.com/bilelmoussaoui/nautilus-git"
fetch.git = "https://github.com/bilelmoussaoui/nautilus-git"

# https://github.com/rafaelmardojai/firefox-gnome-theme

[firefox-gnome-theme]
src.github_tag = "rafaelmardojai/firefox-gnome-theme"
fetch.github = "rafaelmardojai/firefox-gnome-theme"

# https://github.com/rose-pine/kitty
["rose-pine/kitty"]
src.git = "https://github.com/rose-pine/kitty"
fetch.git = "https://github.com/rose-pine/kitty"

# https://github.com/github/copilot.vim
["github/copilot.vim"]
src.git = "https://github.com/github/copilot.vim"
fetch.git = "https://github.com/github/copilot.vim"

[sebaubuntu_libs]
src.github_tag = "sebaubuntu-python/sebaubuntu_libs"
fetch.github = "sebaubuntu-python/sebaubuntu_libs"
