[oh-my-posh]
src.github_tag = "JanDeDobbeleer/oh-my-posh"
fetch.github = "JanDeDobbeleer/oh-my-posh"

[rose-pine]
src.git = "https://github.com/rose-pine/alacritty"
fetch.git = "https://github.com/rose-pine/alacritty"

[nushell]
src.github_tag = "nushell/nushell"
fetch.github = "nushell/nushell"

[plugin-kubectl]
src.git = "https://github.com/blackjid/plugin-kubectl"
fetch.git = "https://github.com/blackjid/plugin-kubectl"

[Boxfish]
src.git = "https://github.com/MidAutumnMoon/Boxfish"
fetch.git = "https://github.com/MidAutumnMoon/Boxfish"

# https://marketplace.visualstudio.com/

["GitHub.copilot"]
src.vsmarketplace = "GitHub.copilot"
fetch.vsmarketplace = "GitHub.copilot"

["GitHub.copilot-labs"]
src.vsmarketplace = "GitHub.copilot-labs"
fetch.vsmarketplace = "GitHub.copilot-labs"

# The Doki Theme
# Material Icon Theme

["unthrottled.doki-theme"]
src.vsmarketplace = "unthrottled.doki-theme"
fetch.vsmarketplace = "unthrottled.doki-theme"

["PKief.material-icon-theme"]
src.vsmarketplace = "PKief.material-icon-theme"
fetch.vsmarketplace = "PKief.material-icon-theme"

# https://github.com/brunonova/nautilus-admin

[nautilus-admin]
src.github_tag = "brunonova/nautilus-admin"
fetch.github = "brunonova/nautilus-admin"

# https://github.com/madmurphy/nautilus-bluetooth

[nautilus-bluetooth]
src.github_tag = "madmurphy/nautilus-bluetooth"
fetch.github = "madmurphy/nautilus-bluetooth"

# https://github.com/flozz/nautilus-terminal

[nautilus-terminal]
src.github_tag = "flozz/nautilus-terminal"
fetch.github = "flozz/nautilus-terminal"

# https://github.com/bilelmoussaoui/nautilus-git/pull/45

[nautilus-git]
src.git = "https://github.com/bilelmoussaoui/nautilus-git"
fetch.git = "https://github.com/bilelmoussaoui/nautilus-git"

# https://gitlab.gnome.org/GNOME/seahorse-nautilus

[seahorse-nautilus]
src.git = "https://gitlab.gnome.org/GNOME/seahorse-nautilus"
fetch.git = "https://gitlab.gnome.org/GNOME/seahorse-nautilus"
