[oh-my-posh]
src.github_tag = "JanDeDobbeleer/oh-my-posh"
fetch.github = "JanDeDobbeleer/oh-my-posh"

[rose-pine]
src.git = "https://github.com/rose-pine/alacritty"
fetch.git = "https://github.com/rose-pine/alacritty"

[nushell]
src.github_tag = "nushell/nushell"
fetch.github = "nushell/nushell"

[plugin-kubectl]
src.git = "https://github.com/blackjid/plugin-kubectl"
fetch.git = "https://github.com/blackjid/plugin-kubectl"

[Boxfish]
src.git = "https://github.com/MidAutumnMoon/Boxfish"
fetch.git = "https://github.com/MidAutumnMoon/Boxfish"

# https://marketplace.visualstudio.com/

["GitHub.copilot"]
src.vsmarketplace = "GitHub.copilot"
fetch.vsmarketplace = "GitHub.copilot"

["GitHub.copilot-labs"]
src.vsmarketplace = "GitHub.copilot-labs"
fetch.vsmarketplace = "GitHub.copilot-labs"

# The Doki Theme
# Material Icon Theme

["unthrottled.doki-theme"]
src.vsmarketplace = "unthrottled.doki-theme"
fetch.vsmarketplace = "unthrottled.doki-theme"

["PKief.material-icon-theme"]
src.vsmarketplace = "PKief.material-icon-theme"
fetch.vsmarketplace = "PKief.material-icon-theme"
