# https://github.com/rafaelmardojai/firefox-gnome-theme

[firefox-gnome-theme]
src.github_tag = "rafaelmardojai/firefox-gnome-theme"
fetch.github = "rafaelmardojai/firefox-gnome-theme"

# https://github.com/rose-pine/kitty
[rose-pine_kitty]
src.git = "https://github.com/rose-pine/kitty"
fetch.git = "https://github.com/rose-pine/kitty"

# https://github.com/longld/peda
[longld_peda]
src.github_tag = "longld/peda"
fetch.github = "longld/peda"

# https://github.com/oh-my-fish/plugin-bang-bang
[oh-my-fish_plugin-bang-bang]
src.git = "https://github.com/oh-my-fish/plugin-bang-bang"
fetch.git = "https://github.com/oh-my-fish/plugin-bang-bang"

# https://github.com/HarlemSquirrel/gnome-shell-extension-sensory-perception

[gnome-shell-extension-sensory-perception]
src.github = "HarlemSquirrel/gnome-shell-extension-sensory-perception"
fetch.github = "HarlemSquirrel/gnome-shell-extension-sensory-perception"

# For GNOME 44

[vinceliuice_Layan-gtk-theme]
src.github_tag = "vinceliuice/Layan-gtk-theme"
fetch.github = "vinceliuice/Layan-gtk-theme"

[daniruiz_flat-remix-gnome]
src.github_tag = "daniruiz/flat-remix-gnome"
fetch.github = "daniruiz/flat-remix-gnome"

