[rose-pine]
src.git = "https://github.com/rose-pine/alacritty"
fetch.git = "https://github.com/rose-pine/alacritty"

[plugin-kubectl]
src.git = "https://github.com/blackjid/plugin-kubectl"
fetch.git = "https://github.com/blackjid/plugin-kubectl"

# [Boxfish]
# src.git = "https://github.com/MidAutumnMoon/Boxfish"
# fetch.git = "https://github.com/MidAutumnMoon/Boxfish"

# https://github.com/brunonova/nautilus-admin

[nautilus-admin]
src.github_tag = "brunonova/nautilus-admin"
fetch.github = "brunonova/nautilus-admin"

# https://github.com/madmurphy/nautilus-bluetooth

[nautilus-bluetooth]
src.github_tag = "madmurphy/nautilus-bluetooth"
fetch.github = "madmurphy/nautilus-bluetooth"

# https://github.com/flozz/nautilus-terminal

[nautilus-terminal]
src.github_tag = "flozz/nautilus-terminal"
fetch.github = "flozz/nautilus-terminal"

# https://github.com/bilelmoussaoui/nautilus-git/pull/45

[nautilus-git]
src.git = "https://github.com/bilelmoussaoui/nautilus-git"
fetch.git = "https://github.com/bilelmoussaoui/nautilus-git"
