[rose-pine]
src.git = "https://github.com/rose-pine/alacritty"
fetch.git = "https://github.com/rose-pine/alacritty"

# https://github.com/brunonova/nautilus-admin

[nautilus-admin]
src.github_tag = "brunonova/nautilus-admin"
fetch.github = "brunonova/nautilus-admin"

# https://github.com/flozz/nautilus-terminal

[nautilus-terminal]
src.github_tag = "flozz/nautilus-terminal"
fetch.github = "flozz/nautilus-terminal"

# https://github.com/bilelmoussaoui/nautilus-git/pull/45

[nautilus-git]
src.git = "https://github.com/bilelmoussaoui/nautilus-git"
fetch.git = "https://github.com/bilelmoussaoui/nautilus-git"

# https://github.com/rafaelmardojai/firefox-gnome-theme

[firefox-gnome-theme]
src.github_tag = "rafaelmardojai/firefox-gnome-theme"
fetch.github = "rafaelmardojai/firefox-gnome-theme"

# https://github.com/rose-pine/kitty
["rose-pine/kitty"]
src.git = "https://github.com/rose-pine/kitty"
fetch.git = "https://github.com/rose-pine/kitty"

# https://github.com/github/copilot.vim
["github/copilot.vim"]
src.git = "https://github.com/github/copilot.vim"
fetch.git = "https://github.com/github/copilot.vim"

# https://github.com/longld/peda
["longld/peda"]
src.github_tag = "longld/peda"
fetch.github = "longld/peda"

# https://github.com/wawa19933/fish-systemd
["wawa19933/fish-systemd"]
src.git = "https://github.com/wawa19933/fish-systemd"
fetch.git = "https://github.com/wawa19933/fish-systemd"

# https://github.com/HarlemSquirrel/gnome-shell-extension-sensory-perception

[gnome-shell-extension-sensory-perception]
src.github = "HarlemSquirrel/gnome-shell-extension-sensory-perception"
fetch.github = "HarlemSquirrel/gnome-shell-extension-sensory-perception"

# https://github.com/samloader/samloader

[samloader]
src.git = "https://github.com/samloader/samloader"
fetch.git = "https://github.com/samloader/samloader"
