[oh-my-posh]
src.github_tag = "JanDeDobbeleer/oh-my-posh"
fetch.github = "JanDeDobbeleer/oh-my-posh"

[rose-pine]
src.git = "https://github.com/rose-pine/alacritty"
fetch.git = "https://github.com/rose-pine/alacritty"

[nushell]
src.github_tag = "nushell/nushell"
fetch.github = "nushell/nushell"

[plugin-kubectl]
src.git = "https://github.com/blackjid/plugin-kubectl"
fetch.git = "https://github.com/blackjid/plugin-kubectl"

[Boxfish]
src.git = "https://github.com/MidAutumnMoon/Boxfish"
fetch.git = "https://github.com/MidAutumnMoon/Boxfish"

# https://marketplace.visualstudio.com/

["GitHub.copilot"]
src.vsmarketplace = "GitHub.copilot"
fetch.vsmarketplace = "GitHub.copilot"

["GitHub.copilot-labs"]
src.vsmarketplace = "GitHub.copilot-labs"
fetch.vsmarketplace = "GitHub.copilot-labs"

["unthrottled.doki-theme"]
src.vsmarketplace = "unthrottled.doki-theme"
fetch.vsmarketplace = "unthrottled.doki-theme"

["PKief.material-icon-theme"]
src.vsmarketplace = "PKief.material-icon-theme"
fetch.vsmarketplace = "PKief.material-icon-theme"

# https://github.com/swellaby/vscode-rust-pack#included-extensions=

["swellaby.rust-pack"]
src.vsmarketplace = "swellaby.rust-pack"
fetch.vsmarketplace = "swellaby.rust-pack"

["rust-lang.rust-analyzer"]
src.vsmarketplace = "rust-lang.rust-analyzer"
fetch.vsmarketplace = "rust-lang.rust-analyzer"

["serayuzgur.crates"]
src.vsmarketplace = "serayuzgur.crates"
fetch.vsmarketplace = "serayuzgur.crates"

["bungcip.better-toml"]
src.vsmarketplace = "bungcip.better-toml"
fetch.vsmarketplace = "bungcip.better-toml"
