# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  "\"github/copilot.vim\"" = {
    pname = "\"github/copilot.vim\"";
    version = "324ec9eb69e20971b58340d0096c3caac7bc2089";
    src = fetchgit {
      url = "https://github.com/github/copilot.vim";
      rev = "324ec9eb69e20971b58340d0096c3caac7bc2089";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-b3c/EQmObPKnT5pBbhAbAySGt2E+1UC0Zqm2vJJiv/4=";
    };
    date = "2022-12-19";
  };
  "\"longld/peda\"" = {
    pname = "\"longld/peda\"";
    version = "v1.2";
    src = fetchFromGitHub ({
      owner = "longld";
      repo = "peda";
      rev = "v1.2";
      fetchSubmodules = false;
      sha256 = "sha256-vtNJ9WHCUtZmIn/IXwwtKrZx1i/az+gMmW6fLd67QYQ=";
    });
  };
  "\"rose-pine/kitty\"" = {
    pname = "\"rose-pine/kitty\"";
    version = "4dd9bbe6f838e61f0ef7e9ab9625adda34e129ef";
    src = fetchgit {
      url = "https://github.com/rose-pine/kitty";
      rev = "4dd9bbe6f838e61f0ef7e9ab9625adda34e129ef";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-idqwpNC6hWIz5KtEGqL5C+KcUcKc9iPCstP5FQcZZ0I=";
    };
    date = "2022-08-24";
  };
  "\"wawa19933/fish-systemd\"" = {
    pname = "\"wawa19933/fish-systemd\"";
    version = "4e922a28ae183e0ddb28c35b8f1415d2c63f978d";
    src = fetchgit {
      url = "https://github.com/wawa19933/fish-systemd";
      rev = "4e922a28ae183e0ddb28c35b8f1415d2c63f978d";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-km6VgvYO1b3wnmpKrnJUaZUrQiIDl8NetECa33jbLbo=";
    };
    date = "2021-08-05";
  };
  firefox-gnome-theme = {
    pname = "firefox-gnome-theme";
    version = "v108.1";
    src = fetchFromGitHub ({
      owner = "rafaelmardojai";
      repo = "firefox-gnome-theme";
      rev = "v108.1";
      fetchSubmodules = false;
      sha256 = "sha256-1nGpcIG2OLwVi9Y93rJGZXCjJM9mSHHta+6WeqEjZng=";
    });
  };
  gnome-shell-extension-sensory-perception = {
    pname = "gnome-shell-extension-sensory-perception";
    version = "v18";
    src = fetchFromGitHub ({
      owner = "HarlemSquirrel";
      repo = "gnome-shell-extension-sensory-perception";
      rev = "v18";
      fetchSubmodules = false;
      sha256 = "sha256-WyMOMPHsLP0CiHpuhafxT1vEKTgEqPRoQAEMA17pFtU=";
    });
  };
  rose-pine = {
    pname = "rose-pine";
    version = "7c3625f3d0f34359ba114e09b1ba3f3c1bed399a";
    src = fetchgit {
      url = "https://github.com/rose-pine/alacritty";
      rev = "7c3625f3d0f34359ba114e09b1ba3f3c1bed399a";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-fjzKxSXGv0yLmT+VAonRCxlqQldxrHWUQgsOugobFoU=";
    };
    date = "2022-04-30";
  };
}
