pxder:
  token: ENC[AES256_GCM,data:9U3O6HWDTHWGOAAB+J4qNFXyCTdLscL8Q5FLrLtHTUZzS9ZjGb1uN+7erA==,iv:vyttYVS5rGcZ2Su5HgEk9XgrzFfdU+/SNOeDJa2hHc4=,tag:qS75azp1NwZPIApHz51zQA==,type:str]
sops:
  kms: [ ]
  gcp_kms: [ ]
  azure_kv: [ ]
  hc_vault: [ ]
  age:
    - recipient: age1sphcw086snupky9p33hclkpvveg3va56sfqqcvzgv5tqc4wwuq3s9vka95
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMMDRwTTZNWFZvbHNITEta
        VjNraTZrdnpLUUprZFN0MDAzOGtieWxQcUhnCjV3T2tHTmsxWUxpQ2dGOG80Mndl
        Q2M4Qnc0NlpybU1mTmNUQXlVR1JwbkkKLS0tIEExWlJKR1NxSlpSeWNPQnR3Wk9X
        akNBNTVNemMwSFc3RERGRHpWbGsxSFUKv2c5XWArw7E+WXz9YPIKXVgOEqdHBbyj
        pBTD5VHVJT9JgPYjub4k1ghfktAxu+x2GsEMe55kwvCDjUEy6yfUqA==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1wsm66wfr48tchca8g8q39002x2v3yc76t8zqvekh3h2h86fdfyyq05uy5t
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSQUUzK2xQSTlVd2lTZTly
        bjVHczhzclZwcURzeUNHMk96MjVZak90M3hZCnE5a3pUbi9TTUFYZ0ZlSFptS1Zi
        Zmg5TFNRSEV0MDFHWnF4S29YVzNXM1EKLS0tIDM4YjkyKzFpRlkxTnkzbXVXTmd5
        UFlTc2taSHlyem91NGVJUi9UbkpBK0UKOPdVykBowDYvbBCn48llPcLpHFvJ8d4H
        coUeSMx18tI0GdXbGd7FNyR9HIgQsQcB5iOe3g5Mvnl5eUBrKE1NLw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2022-01-30T12:31:25Z"
  mac: ENC[AES256_GCM,data:zQV6Dew5Z5/BzUm+AhlCWql2QntsLH6Zk9XR1r7F0iVcvGwa/BLOC7Ny86nNnGCxG3XbKQdmj6L4DpnOoLGVoeryHCywUqNN9m7SytlYfsTGPkdFJQuwP45czZAitfFARHDv7c6SD981Gy3IMtZEqnMnIJavMEP6263vmV3bptU=,iv:ySN4+PJaxk3weOni8DSDcXCgU5iltuAR8VD9QBAVN6g=,tag:SjJs0PvAnNvV5DTPeUux/g==,type:str]
  pgp: [ ]
  unencrypted_suffix: _unencrypted
  version: 3.7.1
